version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/IIC2173-grupo28-back
hooks:
  ApplicationStop:
    - location: scripts/application-stop.sh
      timeout: 10000
      runas: ubuntu
  AfterInstall:
    - location: scripts/after-install.sh
      timeout: 3000
      runas: ubuntu
  ApplicationStart:
    - location: scripts/application-start.sh
      timeout: 3000
      runas: ubuntu
  ValidateService:
    - location: scripts/validate-service.sh
      timeout: 3000
      runas: ubuntu
