# Usar una imagen base de Node.js
FROM node:16-alpine

# Establecer el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copiar package.json y package-lock.json
COPY job_master/ .

# Instalar dependencias
RUN npm install

# Copiar el resto del código de la aplicación

# Exponer el puerto en el que correrá el Job Master
EXPOSE 4004

# Comando para iniciar el Job Master
CMD ["node", "jobMaster.js"]
