# Usar una imagen base de Node.js
FROM node:16-alpine

# Establecer el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copiar package.json y package-lock.json
COPY workers/ .

# Instalar dependencias
RUN npm install

# Comando para iniciar el Worker
CMD ["node", "worker.js"]
