# Usar una imagen base de Node.js
FROM node:20.12.0

# Establecer el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copiar los archivos de la aplicación al contenedor
COPY webpay/ .

# Instalar las dependencias
RUN npm install
RUN bun install
RUN bunx prisma generate

# Exponer el puerto en el que tu API escucha
EXPOSE 3010

# Comando para ejecutar tu API de webpay
# CMD ["npm", "start"]
CMD ["bun", "run", "index.ts"]
