FROM node:latest
# Create app directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY auth/package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY auth/ .

# This is for documentation only, the port must be exposed manually or in compose definition.
EXPOSE 3003

# Command to start the app
CMD ["npm", "start"]
