# Usar una imagen base de Node.js
FROM node:20.12.0

# Establecer el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copiar los archivos de la aplicación al contenedor
COPY legit_app/ .

# Instalar las dependencias
RUN npm install

# Exponer el puerto en el que tu API escucha
EXPOSE 3000

# Comando para ejecutar tu API
CMD ["npm", "start"]
