# Usar una imagen base de Python
FROM python:3.10-slim

# Establecer el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copiar los archivos de la aplicación al contenedor
COPY brokers ./brokers
# COPY brokers/start.sh ./brokers
COPY brokers/start.sh /app/brokers/start.sh


# Cambiar al directorio brokers
WORKDIR /app/brokers

# Instalar paho-mqtt y requests
RUN pip install paho-mqtt requests

# Hacer el script ejecutable y configurarlo como punto de entrada
RUN chmod +x start.sh
# CMD ["./start.sh"]
CMD ["python3", "flights_mqtt_sub.py"]
