# Usar una imagen base de Python
FROM python:3.10-slim

# Establecer el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copiar los archivos de la aplicación al contenedor
COPY brokers ./brokers

# Cambiar al directorio mqtt
WORKDIR /app/brokers
# Instalar paho-mqtt
RUN pip install paho-mqtt requests

# Comando para ejecutar el script del cliente MQTT
CMD ["python", "flights_mqtt_sub.py"]
