# Usar una imagen base de Node.js
FROM node:20.12.0

# Establecer el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copiar los archivos de la aplicación al contenedor
COPY mqtt ./mqtt

# Cambiar al directorio mqtt
WORKDIR /app/mqtt

# Instalar las dependencias
RUN npm install

# Comando ejecutar el receptor MQTT
CMD ["node", "mqttClient.js"]

