name: Lint Workflow

on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  lint-python:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Check if brokers directory exists
      id: check-broker
      run: |
        if [ -d brokers ]; then
          echo "##[set-output name=exists;]true"
        else
          echo "##[set-output name=exists;]false"
        fi
    - name: Install dependencies and run linter
      if: steps.check-broker.outputs.exists == 'true'
      run: |
        pip install flake8
        flake8 ./brokers

  lint-javascript-api:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'
    - name: Check if legit_app directory exists
      id: check-legit-app
      run: |
        if [ -d legit_app ]; then
          echo "##[set-output name=exists;]true"
        else
          echo "##[set-output name=exists;]false"
        fi

    - name: Install dependencies and run linter
      if: steps.check-legit-app.outputs.exists == 'true'
      run: |
        cd legit_app
        sudo npm install
        chmod -R +x ./node_modules/.bin
        sudo npm run lint

  lint-javascript-auth:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'
    - name: Check if auth directory exists
      id: check-auth
      run: |
        if [ -d auth ]; then
          echo "##[set-output name=exists;]true"
        else
          echo "##[set-output name=exists;]false"
        fi
    - name: Install dependencies and run linter
      if: steps.check-auth.outputs.exists == 'true'
      run: |
        cd auth
        npm install
        npm run lint
